### ISSUE TITLE
Incorrect mega count on frozen pokemons

### ISSUE THREAD

**Issue by melinerunen** [Loreinator/Shuffle-Move#118]
It seems that the mega counter is not adding  correctly acording to the move. As you can see in the next two pictures i use total score and mega speedup. On mega progress there is clearly a better option, like the one in mega speed up and in mega speed up the resluting mega progress sums 2 instead of 4.
[Screenshots](http://imgur.com/a/DXUzu)

Bug report of the after move.
https://www.dropbox.com/s/smee2t74ygn23fc/bugReport_20160402_232625_ART.zip?dl=0

**Comment by Loreinator** [comment]
This is working as intended - mega icons that are frozen don't get counted until they are cleared in their non-frozen state. For megas like Diancie it is tricky to see how many icons were counted since so may are needed to evolve.

I just tested it with Gengar on that same stage, and sure enough - when there is one exposed icon of a match of 3 there is only one icon counted for mega progress.

**Comment by Loreinator** [comment]
If this is different on mobile please let me know, I stopped playing the mobile version after I noticed the absurd power drain and the annoyance to avoid it.
