### ISSUE TITLE
Incorrectly spelled Pokémon names are still present in rosterData.txt after update

### ISSUE THREAD

**Issue by kpwbo** [Loreinator/Shuffle-Move#13]
Hello. :)
After updating to v0.3.18, "Vivillion" and "Terrakiom" are effectively removed from `species.txt`, but they are still present in `rosterData.txt`. It doesn't seem to cause others problems as much as I can see.

![](http://i.imgur.com/E4xxYUK.png)

**Comment by Loreinator** [comment]
The way that the configurations are set up allows this to never be a problem, since the roster data is just a lookup table for what level to grant a given species in the simulation. The important thing is to never delete anything unnecessarily from there, or the teams. If a team value isn't valid it will simply be replaced with either AIR or be deleted entirely (not quite sure what would happen). The good thing is this probably won't be an issue since the only ones to get spelling errors are very unused species.

**Comment by kpwbo** [comment]
In v0.3.18 : In case someone has a "Vivillion", "Terrakiom", or any other non-Pokémon name in their team (whether they are in the Roster data or not), when the team is loaded, the non-Pokémon is not shown in the team panel on the right. However, when trying to access the Edit Team window, nothing happens, so the user can't edit the team.


![](http://i.imgur.com/jYjC0j8.png)


To fix this problem, the user must manually edit the `teamsData.txt` file, replacing the non-Pokémon name with an actual Pokémon name, then restart Shuffle Move.

If the non-Pokémon is "Vivillion" or "Terrakiom", another solution is the open v0.3.17. The non-Pokémon will be shown on the team panel, and the user can access the Edit Team window, remove the non-Pokémon from there, and save.

![](http://i.imgur.com/ftxKtm4.png)

Hopefully, this should solve the problem for the few (if any) who would have saved a team with "Vivillion" or "Terrakiom". :)

**Comment by Loreinator** [comment]
Thanks for looking into this. Although v0.3.17 was only out for 2 hours I feel there might be a few who accidentally added the obviously error-prone species (no icon = possible problems), so its excellent that you've found the workaround for any problems created by it. Sometime tonight I'll check to see what the cause is. Nothing should stop the team editor from loading, so that's a big problem. I'm going to open an issue for that right now actually...
