### ISSUE TITLE
Mega Rayquaza may select fully active species

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#130]
According to /u/avengahM, this board resulted in NO extra erasures from the mega effect. It appears that Mega Rayquaza, Mega Mewtwo, and Mega Banette may select the random species from ALL species, active or not.

https://www.reddit.com/r/ShuffleMove/comments/4h9gqm/shuffle_move_v0352/d2p1cc1

```
STAGE SP_084
MEGA_PROGRESS 13
ROW_1 Coin,Rayquaza,Zygarde-10,Rayquaza,Zygarde-10,Meowstic
FROW_1 false,false,false,false,false,false
ROW_2 Coin,Meowstic,Meowstic_f,Zygarde-10,Coin,Rayquaza
FROW_2 false,false,false,false,false,false
ROW_3 Rayquaza,Rayquaza,Zygarde-10,Rayquaza,Zygarde-10,Meowstic
FROW_3 false,false,false,false,false,false
ROW_4 Zygarde-10,Meowstic_f,Coin,Rayquaza,Rayquaza,Zygarde-10
FROW_4 false,false,false,false,false,false
ROW_5 Rayquaza,Coin,Zygarde-10,Meowstic_f,Coin,Coin
FROW_5 false,false,false,false,false,false
ROW_6 Zygarde-10,Rayquaza,Coin,Coin,Zygarde-10,Zygarde-10
FROW_6 false,false,false,false,false,false
```

**Comment by avengah** [comment]
It's difficult to know exactly how it works because if there's a disruption Pokemon on the board that's of a type that can be removed by the Mega effect, then it can be picked. However, if there aren't any on the board, it'll never be picked. This makes me think it's possibly due to the fact that the male Meowstics were still on the board, but fading out at the time, so the game read them even though they're inactive. I could be wrong though.

**Comment by Loreinator** [comment]
Development version with the fix, please re-open if this does not correct the problem.

Google drive link is: https://drive.google.com/uc?id=0Bwi_f200YyRqWTgzWTl6WUxxS28&export=download

MD5Sum is: E5589592E3C8CA387A243D8C179F4B98
