### ISSUE TITLE
Create a "Result Chooser"

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#133]
As an extension of the Move Chooser, there should be a "Result Chooser" window with a grid of its own, and a panel showing each result's average statistics. The % chance of occurrence should be listed for each result, with the top result as the selected entry by default.

Reuse of the Move Chooser and Grid Panels should make implementation relatively efficient.

**Comment by krazyken** [comment]
I think this could actually be mostly implemented in the move chooser. Instead of calculating an average outcome for a move, we list all/(top x most likely) outcomes in the move chooser for each move with probability. This could increase speed due to no longer needing to run 100 simulations per move. 
in the short term a user can do/undo move to see the results. In the long term maybe it would be possible to overlay an X on the icons that will be removed or an O on disappearing barriers and so forth.
