### ISSUE TITLE
Program stuck at simulation started

### ISSUE THREAD

**Issue by Zebaahx** [Loreinator/Shuffle-Move#150]
[bugReport_20160525_005158_CLT.zip](https://github.com/Loreinator/Shuffle-Move/files/280964/bugReport_20160525_005158_CLT.zip)

i've checked all settings, i've reduced the simulations to 5 but still i get no results, tried running as admin, running in compatibitility mode, but nothing works

**Comment by Loreinator** [comment]
Problem found and solved!

**Comment by Zebaahx** [comment]
That was fast. Thank you very much!! :D Waiting for new release to test

**Comment by Loreinator** [comment]
Yup, Github issue + bug report zip means I can very quickly jump into the 'solving the problem' phase, instead of not being aware of it or not being able to reproduce it. Those bug report zips include every config file I would need to exactly replicate the situation your client is in, if its a problem with the program itself.
