### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by aabrosov** [Loreinator/Shuffle-Move#163]
The icons look a little different.
For example glalie.
Perhaps they need to update?

**Comment by Loreinator** [comment]
Can you give an example of where they differ? I get all the icons from http://www.serebii.net/shuffle/pokemon.shtml since I have permission from them to re-use their icons in Shuffle Move. They appear to match exactly, and I can't see any difference with the source icon files. 

Note: The icon files are not used as-is in the default resolution, they are re-scaled and rendered to be easily recognizable at any scale level (user-defined in preferences.txt).

**Comment by aabrosov** [comment]
<img width="64" alt="screenshot" src="https://cloud.githubusercontent.com/assets/9800665/16457209/103cda24-3e34-11e6-8c4f-0c2a9bf7e616.png">
<img width="64" alt="appicon" src="https://cloud.githubusercontent.com/assets/9800665/16457210/103d5f8a-3e34-11e6-82dc-e1c497cb893c.png">

**Comment by aabrosov** [comment]
All icons everywhere in the internet are from one source, I think.
But now in mobile app this icon looks darker and mouth lighter.
I think it was changed in apk version 1.6.0.

**Comment by Loreinator** [comment]
What source has the icons as they are in the current build?

**Comment by aabrosov** [comment]
I'm not sure, I just get it from the screen.
Sure somebody could get it from current build :-)
