### ISSUE TITLE
New species not showing

### ISSUE THREAD

**Issue by jimbo4273** [Loreinator/Shuffle-Move#210]
[bugReport_20161020_124534_CDT.zip](https://github.com/Loreinator/Shuffle-Move/files/542436/bugReport_20161020_124534_CDT.zip)

**Comment by Loreinator** [comment]
> I have been creating new species data for the latest releases, and they aren't showing up.

Do you mean they don't have icons, or they don't appear in the roster at all?

**Comment by jimbo4273** [comment]
They appear, but after I save and exit, they don't show up at all.

**Comment by Loreinator** [comment]
I'll have to take a look when I get home then. In the meantime, try using the latest development build instead of manually adding in species yourself: 

https://drive.google.com/open?id=0Bwi_f200YyRqfm5fOWMtbkVrd0RhQUJyTDR6V29WZFFBd0o4cl95VjlqUTkyNDRicS1GOVE

I generally leave it a couple of days before releasing in case there are corrections to be done, or if new details arise.

**Comment by jimbo4273** [comment]
OK. Thanks for the quick response!

**Comment by Loreinator** [comment]
From the log it looks like you may have been manually editing the species files incorrectly: 

> [Oct 20, 2016 12:41:14 PM] [FINE] Cannot parse config entry, key: Gourgeist type: SPECIES value: (Spooky) 3211 60 GHOST SPOOKIFY 

Please ensure that you properly escape space characters, or it won't parse it properly. For example, the "winking" species are given the Name: "Bulbasaur_w". It is through the i18n entries that it becomes "Bulbasaur (Winking)". In general I do not recommend manually editing these files, or you will encounter problems when updating to a new version (missing species).
