### ISSUE TITLE
Fonts on High DPI screens are incredibly small

### ISSUE THREAD

**Issue by Icehawk78** [Loreinator/Shuffle-Move#239]
I'm almost unable to click on most buttons on the screen because of the tiny size on my Microsoft Surface. The culprit from some initial searching seems to be the usage of Swing for the UI, which does not support display DPI scaling, and thus just keeps everything really tiny.

Recommended suggestions were to use JavaFX for the GUI.

Naturally, I'm assuming this would be a major rewrite and should be prioritized appropriately if at all, but I didn't see the issue reported elsewhere yet.

**Comment by Loreinator** [comment]
https://github.com/Loreinator/Shuffle-Move/wiki/Display-Size-Configuration#preference-keys-scaling---coming-in-v0347

Try setting these keys in your preferences.txt file to something like 400 or 800 instead of the 100 default. This may help enlarge the UI enough to be useful for you.

INTEGER FONT_SIZE_SCALING 100
INTEGER IMAGE_SCALING 100
INTEGER BORDER_SCALING 100

**Comment by Icehawk78** [comment]
That seems to have worked. Not sure if you'd like to leave this issue open to auto-detect the scaling. If not, manually setting it was sufficient for me to mark this as complete and close it.

**Comment by Loreinator** [comment]
I found this: 
http://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display
https://bugs.openjdk.java.net/browse/JDK-8080153

Once openjdk issue JDK-8080153 is resolved, I may be able to force this to be fixed by adding an option to the launching properties.
