### ISSUE TITLE
Pikachu overflow

### ISSUE THREAD

**Issue by Manitary** [Loreinator/Shuffle-Move#267]
Since we now have more than 10 different Pikachu in the game, I do not know how to input the new one in  the species.txt file!

(I am updating everything else, so do not bother with the reminder of the update)

**Comment by Loreinator** [comment]
I just made a change to the species data storage pattern and representations. It now has the number as a double, instead of an integer. To separate between the Pikachu species, just set the new ones to a .## version of the base number. 

example: 

    SPECIES Pikachu_sm 168 50 ELECTRIC FLASH_MOB

The next one could be:

    SPECIES Pikachu_after_sm 168.1 50 ELECTRIC FLASH_MOB

Since it uses doubles, there should be no practical limit to the variations we can add now. Even just using the first decimal place, this now allows up to 100 versions of each species.

**Comment by Loreinator** [comment]
See commit: https://github.com/Loreinator/Shuffle-Move/commit/ae97b6e7493942778e2d3ea87693b97e4c9bf267
