### ISSUE TITLE
Flash mob damage isn't calculated properly

### ISSUE THREAD

**Issue by ZeroRin** [Loreinator/Shuffle-Move#297]
flash mob deals damage according to the number of one type of pokemon on board
but the program seems to only calculated the pokemon that triggered the skill. just same as crowd control

**Comment by ZeroRin** [comment]
![1fhiunmcli g1np7lossm1g](https://user-images.githubusercontent.com/14952735/27273354-4e5fbbf2-5501-11e7-9898-ebc57f631cd2.png)

**Comment by Manitary** [comment]
Can confirm, tried with Keldeo and other water types.

I don't know much how to interpret all the functions, but at a glance the problem could be related to these line in Effects.java:

`Species effectSpecies = task.getEffectSpecies(comboEffect.getCoords());
int num = task.findMatches(36, true,(r, c, s) -> (s.equals(effectSpecies) [...]`

If getEffectSpecies looks for the icons of the same species on the board, that's where the problem is.

**Comment by Loreinator** [comment]
Found the issue and fixed it in the master branch, it'll be part of the next release

It was just a difference between checking for species that equal the effect species, versus checking for species that match the effect species' type. 

Oh, btw this line:
`Species effectSpecies = task.getEffectSpecies(comboEffect.getCoords());`
Is just the way that the task allows the effect to look up what species is on the coordinate of the match.
