### ISSUE TITLE
French Translation ko

### ISSUE THREAD

**Issue by slhad** [Loreinator/Shuffle-Move#329]
The last functional version for French is 0.3.111.

**Comment by slhad** [comment]
Everything is in english like every translations are missing

**Comment by Royalnb** [comment]
There were at least 2 issues on the 8th August update (0.3.112).
The fist one I already fixed was Basculin=Bargantua (Motif bleu) instead of Basculin_b=Bargantua (Motif bleu).
I thought that was enough but with today's release I realised that something else was wrong.

I found out that the lines 674 and 676 : Deerling_s=Vivaldaim (Forme \u00et\u00e) and Sawsbuck_s=Haydaim (Forme \u00et\u00e) are off too and should be Deerling_s=Vivaldaim (Forme \u00e9t\u00e9) and Sawsbuck_s=Haydaim (Forme \u00e9t\u00e9) 

But I can't figure out how to build the project myself to check if the translations would be okay again.

**Comment by slhad** [comment]
I waited for the 0.3.113 release to see if it was fixed by the 2 issues of the 8th August but it did not change anything :(

All the translations of Pokemon in French have disappeared.

**Comment by Loreinator** [comment]
The issue was that the encoding for the "Forme \u00et\u00e" is a malformed unicode value, so the interpreter treated the entire file as corrupted. I've fixed this to "Forme \u00e9t\u00e9" in this commit: 

https://github.com/Loreinator/Shuffle-Move/commit/d62934fbc221ed8bf77c18e0199418222345129b

I verified that this does fix the issue in my development environment.

**Comment by slhad** [comment]
Thanks @Loreinator
