### ISSUE TITLE
Quirky+ and Quirky trigger too often

### ISSUE THREAD

**Issue by FlipzMCL** [Loreinator/Shuffle-Move#4]
Hello,

I've been using Shuffle Move for Weekend Meowth and a few other levels, but unfortunately the move chooser seems to rank my potential moves based on assuming Quirky will trigger, rather than assuming it won't.  This dramatically skews the results/ranking, which in turn leads to many wasted moves (which, while not a huge issue in Weekend Meowth, is VERY problematic in S-ranking stages).  Is there any way we can get a preferences option to disable Quirky/Quirky+ simulation so that we can have more accurate results overall?

**Comment by Loreinator** [comment]
According to the best sources available, the Quirky/Quirky+ rates are accurately being simulated, so this should just be a problem with ranking them more intuitively. For now a simple workaround is to examine the list of results yourself and go for the one that has the highest minimum instead of the highest average - as usual, proper use requires some user-based judgement to select the best option. 

We have some choice in how to approach this though: 

1. Add an option to disable/force-on different effects, this will obviously need somewhere to go in the interface. The best place I can think of would be in the move preferences window since it affects the simulation deeply.
2. Improve sorting to include configurable sorting modes, instead of just a handful of hard-coded options. This would require a rewrite of the rendering, usage, and i18n for the grading modes... but it would likely give a lot better flexibility for more users than option 1 on its own. 
3. Do both 1 and 2, allowing a far greater degree of access to fiddle with sorting and effect occurrence in the simulation.

Do you think that would address your concerns, or is there some other way you would approach this?

Depending on time availability I may be able to do option 1 quickly, but option 2 will require a new GUI and 4+ hours of development on just rewriting code pathways and thoroughly testing the new configurable system.

**Comment by FlipzMCL** [comment]
Option 1 seems like the best option--I actually went to the move preferences window the first time I realized what was happening, thinking there might already be an option for it. :+1: 

Obviously Option 3 is the "in a perfect world" ideal, but as you mentioned it's a lot of work on your end--maybe it's something you can throw onto the planned features list, particularly if its development could be rolled into the mobile/web app version development (since a lot of things probably need to be rewritten as part of that development anyway)?

**Comment by Loreinator** [comment]
Option 1 complete.

See here:
https://github.com/Loreinator/Shuffle-Move/commit/3e8f6569517846105b379371635ff28e1ac74710

Given that the core idea of this issue is now addressed, I'm closing this issue.

I'll remake a new issue to specifically target the perfect world fix - configurable grading modes.

**Comment by Loreinator** [comment]
https://github.com/Loreinator/Shuffle-Move/issues/16
