### ISSUE TITLE
Clear board states when loading default

### ISSUE THREAD

**Issue by Loreinator** [Loreinator/Shuffle-Move#91]
>Please could you put an option to reset a level to its initial state? What I'm trying to do is grind Heatmor for coins. When I finish, I have to click the menu at the bottom and pick a different level then Heatmor again, to reset the score and turns etc., which is an unwieldy way of doing it. I also have to set Mega progress to 0.
> 
>Maybe the "Load Default" menu option at the top could also set everything else to default as well? Thanks!

https://www.reddit.com/r/ShuffleMove/comments/3qcs7b/shuffle_move_v0336/cwphd70

**Comment by avengah** [comment]
Now that I think about it, resetting Mega progress shouldn't necessarily happen. For example, someone might want to use Shuffle Move for a turn-based competition where Mega Start is available. I suppose it's a behaviour that could be toggled, maybe, since it's hard to say whether people would want it reset or not for each individual case. Or, of course, if the player ticks the box at the start of the level, then don't reset it. (But only at the start of the level, since the player might tick the box part way through if skyfall causes the Mega to evolve.)

**Comment by Loreinator** [comment]
Well... Loading the default board should only happen at the start of a level. 

So, the plan is that when load default is triggered:

- Mega progress reset
- Score set to 0
- Moves set to stage starting moves
- Board replaced with the default board if it exists, otherwise emptied

**Comment by avengah** [comment]
That seems fine. I'm sure people won't mind clicking one box each time they restart if they are using Mega Start; it's simple enough to do!

**Comment by Loreinator** [comment]
fixed in next release
