### ISSUE TITLE
Application Hang/Not Responding

### ISSUE THREAD

**Issue by kantha88** [Loreinator/Shuffle-Move#99]
Hi Loreinator, first of all, million thanks to you for making this awesome app.

I have been using this app for quite some time on different laptop, but since I have ben using new laptop, it occasionally hangs. I have set move calculation for 500 iterations. Attached is the logs in below link. Sorry if I have missed out any information, kindly let me know if you require any additional information.

https://www.dropbox.com/s/effuaj59uw7au08/bugReport_20151219_111136_SGT.zip?dl=0

**Comment by Loreinator** [comment]
I just tried out the board you had when the bug report was submitted, it computed in about 6 seconds on my computer. My guess is that it is just taking a long time due to poor hardware. If this problem occurs with a different board with more severe problems after reducing your iterations to 50, please submit another bug report and I'll see if there is something more going on. Also provide OS version and Java version when you do.
